# Generated by Django 4.1.4 on 2023-03-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Add_Photos", new_name="Add_Photo",),
        migrations.RenameModel(old_name="Add_videos", new_name="Add_video",),
    ]
