# Generated by Django 4.1.7 on 2023-04-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_rename_add_photos_add_photo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="add_video", old_name="video", new_name="video_template",
        ),
    ]
