# Generated by Django 4.1.7 on 2023-04-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_card_description_alter_description_description"),
    ]

    operations = [
        migrations.DeleteModel(name="Description",),
    ]
