# Generated by Django 4.1.7 on 2023-04-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_card_long_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="long_description",
            field=models.TextField(default="type here", max_length=8000),
        ),
    ]
