# Generated by Django 4.1.4 on 2023-03-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog_images/")),
                ("heading", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("detail_description", models.TextField()),
                (
                    "background_image",
                    models.ImageField(upload_to="blog_background_images/"),
                ),
                ("youtube_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog_cards/")),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
