# Generated by Django 4.1.7 on 2023-04-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_astrology_nature_political_religious_social_sports_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astrology",
            name="image",
            field=models.ImageField(default="input image", upload_to="blog/"),
        ),
        migrations.AddField(
            model_name="astrology",
            name="long_description1",
            field=models.TextField(default="Type Here"),
        ),
        migrations.AddField(
            model_name="astrology",
            name="long_description2",
            field=models.TextField(blank=True, default="Type Here"),
        ),
        migrations.AddField(
            model_name="astrology",
            name="title1",
            field=models.CharField(default="Type Here", max_length=100),
        ),
        migrations.AddField(
            model_name="astrology",
            name="title2",
            field=models.CharField(blank=True, default="Type Here", max_length=100),
        ),
        migrations.AddField(
            model_name="nature",
            name="image",
            field=models.ImageField(default="input image", upload_to="blog/"),
        ),
        migrations.AddField(
            model_name="nature",
            name="long_description1",
            field=models.TextField(default="Type Here"),
        ),
        migrations.AddField(
            model_name="nature",
            name="long_description2",
            field=models.TextField(blank=True, default="Type Here"),
        ),
        migrations.AddField(
            model_name="nature",
            name="title1",
            field=models.CharField(default="Type Here", max_length=100),
        ),
        migrations.AddField(
            model_name="nature",
            name="title2",
            field=models.CharField(blank=True, default="Type Here", max_length=100),
        ),
        migrations.AddField(
            model_name="political",
            name="image",
            field=models.ImageField(default="input image", upload_to="blog/"),
        ),
        migrations.AddField(
            model_name="political",
            name="long_description1",
            field=models.TextField(default="Type Here"),
        ),
        migrations.AddField(
            model_name="political",
            name="long_description2",
            field=models.TextField(blank=True, default="Type Here"),
        ),
        migrations.AddField(
            model_name="political",
            name="title1",
            field=models.CharField(default="Type Here", max_length=100),
        ),
        migrations.AddField(
            model_name="political",
            name="title2",
            field=models.CharField(blank=True, default="Type Here", max_length=100),
        ),
        migrations.AddField(
            model_name="religious",
            name="image",
            field=models.ImageField(default="input image", upload_to="blog/"),
        ),
        migrations.AddField(
            model_name="religious",
            name="long_description1",
            field=models.TextField(default="Type Here"),
        ),
        migrations.AddField(
            model_name="religious",
            name="long_description2",
            field=models.TextField(blank=True, default="Type Here"),
        ),
        migrations.AddField(
            model_name="religious",
            name="title1",
            field=models.CharField(default="Type Here", max_length=100),
        ),
        migrations.AddField(
            model_name="religious",
            name="title2",
            field=models.CharField(blank=True, default="Type Here", max_length=100),
        ),
        migrations.AddField(
            model_name="social",
            name="image",
            field=models.ImageField(default="input image", upload_to="blog/"),
        ),
        migrations.AddField(
            model_name="social",
            name="long_description1",
            field=models.TextField(default="Type Here"),
        ),
        migrations.AddField(
            model_name="social",
            name="long_description2",
            field=models.TextField(blank=True, default="Type Here"),
        ),
        migrations.AddField(
            model_name="social",
            name="title1",
            field=models.CharField(default="Type Here", max_length=100),
        ),
        migrations.AddField(
            model_name="social",
            name="title2",
            field=models.CharField(blank=True, default="Type Here", max_length=100),
        ),
        migrations.AddField(
            model_name="sports",
            name="image",
            field=models.ImageField(default="input image", upload_to="blog/"),
        ),
        migrations.AddField(
            model_name="sports",
            name="long_description1",
            field=models.TextField(default="Type Here"),
        ),
        migrations.AddField(
            model_name="sports",
            name="long_description2",
            field=models.TextField(blank=True, default="Type Here"),
        ),
        migrations.AddField(
            model_name="sports",
            name="title1",
            field=models.CharField(default="Type Here", max_length=100),
        ),
        migrations.AddField(
            model_name="sports",
            name="title2",
            field=models.CharField(blank=True, default="Type Here", max_length=100),
        ),
        migrations.AlterField(
            model_name="astrology",
            name="description",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="nature",
            name="description",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="political",
            name="description",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="religious",
            name="description",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="social",
            name="description",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="sports",
            name="description",
            field=models.TextField(max_length=200),
        ),
    ]
