# Generated by Django 4.1.4 on 2023-02-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bannerimage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=10000, null=True),
                ),
                ("banner_background", models.ImageField(upload_to="images/")),
                ("banner_image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
