# Generated by Django 4.1.4 on 2023-03-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_about_guruji"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="about/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog/")),
                ("heading", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("detail_description", models.TextField()),
                ("background_image", models.ImageField(upload_to="blog/")),
                ("youtube_link", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="gallery/")),
                ("add_button", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GurujiWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="guruji_words/")),
                ("heading", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("add_button", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner_description", models.CharField(max_length=255)),
                ("banner_background", models.ImageField(upload_to="banners/")),
                ("banner_image", models.ImageField(upload_to="banners/")),
            ],
        ),
        migrations.CreateModel(
            name="Horoscope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("panchang_image", models.ImageField(upload_to="horoscope/")),
                ("nakshatra", models.CharField(max_length=255)),
                ("tithi", models.CharField(max_length=255)),
                ("sunrise", models.CharField(max_length=255)),
                ("sunset", models.CharField(max_length=255)),
                ("yoga", models.CharField(max_length=255)),
                ("rashi", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("update_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LatestFromGuruji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="latest_from_guruji/")),
                ("book", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MeetGuruji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="meet_guruji/")),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="OtherAbout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="other_about/")),
                ("background_image", models.ImageField(upload_to="other_about/")),
                ("types_details", models.TextField()),
                (
                    "addon_images",
                    models.ImageField(blank=True, upload_to="other_about/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("image", models.ImageField(upload_to="products/")),
                ("image_pin", models.ImageField(upload_to="products/")),
                ("short_description", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("long_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ResolveProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="resolve_problem/")),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_image", models.ImageField(upload_to="cards/")),
                ("card_heading", models.CharField(max_length=255)),
                ("card_description", models.CharField(max_length=255)),
                ("card_button", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="testimonial/")),
                ("description", models.TextField()),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TodaysHoroscope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("rasifal", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(name="About_guruji",),
        migrations.DeleteModel(name="Bannerimage",),
    ]
