# Generated by Django 4.1.4 on 2023-03-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_about_blog_festival_gallery_gurujiwords_homepage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutGuruji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="about/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_no", models.IntegerField(verbose_name=10)),
                ("email_id", models.EmailField(max_length=254)),
                ("Address", models.CharField(max_length=255)),
                ("social_media_links", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(old_name="HomePage", new_name="BannerImage",),
        migrations.DeleteModel(name="About",),
        migrations.DeleteModel(name="Blog",),
        migrations.DeleteModel(name="Gallery",),
        migrations.DeleteModel(name="LatestFromGuruji",),
        migrations.DeleteModel(name="MeetGuruji",),
        migrations.DeleteModel(name="OtherAbout",),
        migrations.DeleteModel(name="Products",),
        migrations.DeleteModel(name="Services",),
        migrations.RemoveField(model_name="gurujiwords", name="add_button",),
    ]
