# Generated by Django 4.1.4 on 2023-03-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_aboutguruji_appointment_footer_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="footer", name="social_media_links",),
        migrations.AddField(
            model_name="footer",
            name="facebook",
            field=models.CharField(
                default="https://www.facebook.com/my-page", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="footer",
            name="instagram",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="footer",
            name="twitter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
