# Generated by Django 4.1.4 on 2023-03-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_footer_contact_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="address",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bannerimage",
            name="banner_description",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="footer", name="Address", field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="footer",
            name="contact_no",
            field=models.CharField(max_length=12),
        ),
    ]
