# Generated by Django 4.1.4 on 2023-03-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_appointment_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerimage",
            name="banner_background",
            field=models.ImageField(blank=True, upload_to="banners/"),
        ),
    ]
