# Generated by Django 4.1.4 on 2023-03-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_bannerimage_banner_background"),
    ]

    operations = [
        migrations.CreateModel(
            name="Our_Services_Cards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="our_services_cards/")),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(name="Horoscope",),
    ]
