# Generated by Django 4.1.4 on 2023-03-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_our_services_cards_delete_horoscope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gurujiwords",
            name="image",
            field=models.ImageField(blank=True, upload_to="guruji_words/"),
        ),
    ]
