# Generated by Django 4.1.4 on 2023-03-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_gurujiwords_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aaj_ka_Rashifal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Aries", models.TextField()),
                ("Taurus", models.TextField()),
                ("Gemini", models.TextField()),
                ("Cancer", models.TextField()),
                ("Leo", models.TextField()),
                ("Virgo", models.TextField()),
                ("Libra", models.TextField()),
                ("Scorpio", models.TextField()),
                ("Sagittarius", models.TextField()),
                ("Capricorn", models.TextField()),
                ("Aquarius", models.TextField()),
                ("Pisces", models.TextField()),
            ],
        ),
        migrations.DeleteModel(name="TodaysHoroscope",),
    ]
