# Generated by Django 4.1.7 on 2023-04-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_todays_updates"),
    ]

    operations = [
        migrations.RemoveField(model_name="festival", name="date",),
        migrations.RemoveField(model_name="festival", name="description",),
        migrations.AddField(
            model_name="festival",
            name="april",
            field=models.TextField(default="february"),
        ),
        migrations.AddField(
            model_name="festival",
            name="august",
            field=models.TextField(default="february"),
        ),
        migrations.AddField(
            model_name="festival",
            name="december",
            field=models.TextField(default="february"),
        ),
        migrations.AddField(
            model_name="festival",
            name="february",
            field=models.TextField(default="february"),
        ),
        migrations.AddField(
            model_name="festival",
            name="january",
            field=models.TextField(default="february"),
        ),
        migrations.AddField(
            model_name="festival",
            name="july",
            field=models.TextField(default="february"),
        ),
        migrations.AddField(
            model_name="festival",
            name="june",
            field=models.TextField(default="february"),
        ),
        migrations.AddField(
            model_name="festival",
            name="march",
            field=models.TextField(default="february"),
        ),
        migrations.AddField(
            model_name="festival",
            name="may",
            field=models.TextField(default="february"),
        ),
        migrations.AddField(
            model_name="festival",
            name="november",
            field=models.TextField(default="february"),
        ),
        migrations.AddField(
            model_name="festival",
            name="october",
            field=models.TextField(default="february"),
        ),
        migrations.AddField(
            model_name="festival",
            name="september",
            field=models.TextField(default="february"),
        ),
        migrations.AddField(
            model_name="todays_updates",
            name="short_description",
            field=models.TextField(default="guruji", max_length=50),
        ),
    ]
