# Generated by Django 4.1.4 on 2023-03-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutOtherPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="about/")),
                ("background_image", models.ImageField(upload_to="about/")),
                ("types_details", models.TextField()),
                (
                    "addon_image1",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                (
                    "addon_image2",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                (
                    "addon_image3",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Heading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="about/")),
                ("heading", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LatestFromGuruji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="latest_from_guruji/")),
                ("book", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MeetGuruji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="meet_guruji/")),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="SecondTopImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="second_top_image/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TopImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_1", models.ImageField(upload_to="top_image/")),
                ("image_2", models.ImageField(upload_to="top_image/")),
                ("image_3", models.ImageField(upload_to="top_image/")),
                ("description", models.TextField()),
            ],
        ),
    ]
