# Generated by Django 4.1.7 on 2023-04-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gorchar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="second_top_image/")),
                ("title1", models.CharField(max_length=100)),
                ("description1", models.TextField()),
                ("title2", models.CharField(max_length=100)),
                ("description2", models.TextField()),
                ("title3", models.CharField(max_length=100)),
                ("description3", models.TextField()),
                ("title4", models.CharField(max_length=100)),
                ("description4", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Guruji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="about/")),
                ("guruji_image", models.ImageField(upload_to="guruji_images/")),
                ("meet_guruji_image", models.ImageField(upload_to="meet_guruji/")),
                ("book_image", models.ImageField(upload_to="book_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Horoscope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="second_top_image/")),
                ("title1", models.CharField(max_length=100)),
                ("description1", models.TextField()),
                ("title2", models.CharField(max_length=100)),
                ("description2", models.TextField()),
                ("title3", models.CharField(max_length=100)),
                ("description3", models.TextField()),
                ("title4", models.CharField(max_length=100)),
                ("description4", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Kundli",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="second_top_image/")),
                ("title1", models.CharField(max_length=100)),
                ("description1", models.TextField()),
                ("title2", models.CharField(max_length=100)),
                ("description2", models.TextField()),
                ("title3", models.CharField(max_length=100)),
                ("description3", models.TextField()),
                ("title4", models.CharField(max_length=100)),
                ("description4", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Vedic_astrology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="second_top_image/")),
                ("title1", models.CharField(max_length=100)),
                ("description1", models.TextField()),
                ("title2", models.CharField(max_length=100)),
                ("description2", models.TextField()),
                ("title3", models.CharField(max_length=100)),
                ("description3", models.TextField()),
                ("title4", models.CharField(max_length=100)),
                ("description4", models.TextField()),
            ],
        ),
        migrations.DeleteModel(name="AboutOtherPart",),
        migrations.DeleteModel(name="Heading",),
        migrations.DeleteModel(name="LatestFromGuruji",),
        migrations.DeleteModel(name="MeetGuruji",),
        migrations.DeleteModel(name="SecondTopImage",),
        migrations.DeleteModel(name="TopImage",),
    ]
