# Generated by Django 4.1.7 on 2023-04-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_gorchar_guruji_horoscope_kundli_vedic_astrology_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Guruji",),
    ]
