# Generated by Django 4.1.7 on 2023-04-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_delete_guruji"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guruji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="about/")),
                ("image2", models.ImageField(upload_to="about/")),
                ("image3", models.ImageField(upload_to="about/")),
                ("image4", models.ImageField(upload_to="about/")),
                ("image5", models.ImageField(upload_to="about/")),
                ("image6", models.ImageField(upload_to="about/")),
                ("guruji_image", models.ImageField(upload_to="guruji_images/")),
                ("meet_guruji_image", models.ImageField(upload_to="meet_guruji/")),
                ("meet_guruji_image2", models.ImageField(upload_to="meet_guruji/")),
                ("meet_guruji_image3", models.ImageField(upload_to="meet_guruji/")),
                ("book_image", models.ImageField(upload_to="book_images/")),
                ("book_url", models.URLField()),
                ("book_image2", models.ImageField(upload_to="book_images/")),
                ("book2_url", models.URLField()),
                ("book_image3", models.ImageField(upload_to="book_images/")),
                ("book3_url", models.URLField()),
            ],
        ),
    ]
