# Generated by Django 4.1.7 on 2023-04-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_guruji"),
    ]

    operations = [
        migrations.RemoveField(model_name="guruji", name="description",),
        migrations.RemoveField(model_name="guruji", name="guruji_image",),
    ]
