# Generated by Django 4.1.7 on 2023-04-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0006_delete_guruji"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guruji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="about/")),
                ("image2", models.ImageField(upload_to="about/")),
                ("image3", models.ImageField(upload_to="about/")),
                ("image4", models.ImageField(upload_to="about/")),
                ("image5", models.ImageField(upload_to="about/")),
                ("image6", models.ImageField(upload_to="about/")),
                ("meet_guruji_image", models.ImageField(upload_to="meet_guruji/")),
                ("date1", models.DateField()),
                ("location1", models.URLField()),
                ("meet_guruji_image2", models.ImageField(upload_to="meet_guruji/")),
                ("date2", models.DateField()),
                ("location2", models.URLField()),
                ("meet_guruji_image3", models.ImageField(upload_to="meet_guruji/")),
                ("date3", models.DateField()),
                ("location3", models.URLField()),
                ("book_image", models.ImageField(upload_to="book_images/")),
                ("book_url", models.URLField()),
                ("book_image2", models.ImageField(upload_to="book_images/")),
                ("book2_url", models.URLField()),
                ("book_image3", models.ImageField(upload_to="book_images/")),
                ("book3_url", models.URLField()),
            ],
        ),
    ]
